load: False
load_idx: 1
dir: ../vsem_models/fivesent_wordvec/model
seq_len: 25
wordvec_dims: 100
encode_hid: 512
latent_dims: 256
decode_hid: 512
learning_rate: 0.0001
keep_prob: 0.5
kl_alpha_rate: 0.000005
batch_size: 50
train_steps: 10000000
